### ISSUE TITLE
libports: add libpq and libpqxx libraries

### ISSUE THREAD

**Issue by alexygallar2** [genodelabs/genode-world#1]
Libraries for connection with database PostgreSQL server

**Comment by alexygallar2** [comment]
This commit is the support for libraries libpq and libpqxx.
f990d11b972765e3abca79f33719d509e26804e9

**Comment by alexygallar2** [comment]
This other commit is the support for some examples of use the libraries libpq and libpqxx.
540d0c657943cb787b2b62ff9557a03d4f0a9242

**Comment by alexygallar2** [comment]
Lo siento por el retraso en subir los cambios.

**Comment by nfeske** [comment]
Thanks for reviving the issue. I am a bit puzzled about how to merge your commits though. When clicking on them, they appear (according to the URL) as part of the genodelabs/genode-world repository, which does not make much sense. You don't have a public fork of this repository in your account where I could fetch it. May I ask how you published those commits? Can you give me a hint how (from where) to cherry-pick them?

**Comment by chelmuth** [comment]
Maybe here https://github.com/xeos-team/genode-world/commits/issue1?

**Comment by alexygallar2** [comment]
Yes , In the URL that says @chelmuth
https://github.com/xeos-team/genode-world/commits/issue1

**Comment by nfeske** [comment]
Thanks for showing me the way to go... ;-)

**Comment by alexygallar2** [comment]
Thank you for spending the time to maintain some form of community contributions.

**Comment by alexygallar2** [comment]
Sorry for the confusion I have caused

**Comment by nfeske** [comment]
You are very welcome. Thank *you* for contributing to Genode! :-)

**Comment by nfeske** [comment]
Merged into master.
