### ISSUE TITLE
Split Libretro frontend and cores to seperate repo

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#100]
I would like to spin off the Libretro stuff into a separate repository for better visibility. May I have the blessing to 'fork' this software from Genode Labs, and extend copyright to future contributors?

**Comment by ehmry** [comment]
New repo forked and pruned at https://github.com/ehmry/genode-libretro.

**Comment by nfeske** [comment]
Of course you have our blessing! :-)

**Comment by nfeske** [comment]
Do you intend to craft a commit that removes the relocated code from the world repository?

**Comment by ehmry** [comment]
Yes, fixed at d44b4ab0e67fade533da2d5fb7aba44e68b4be12.

**Comment by nfeske** [comment]
Thanks. Merged to master.

**Comment by nfeske** [comment]
BTW, you may consider adjusting the licensing headers of your source codes. Right now, some of the files state GPLv2 whereas the top-level LICENSE file of your new repository states GPLv3.
