### ISSUE TITLE
sqlite: remove use of deprecated API

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode-world#102]
The port of sqlite does not build anymore because of the changes of Genode's VFS. While trying to build it, I noticed that it uses the deprecated env along with deprecated connection constructors.

**Comment by ehmry** [comment]
I suggest removing the SQLite port completely. There is a problem with the library making a `fcntl` call that we don't support, but that is something we have to fix ourselves in libc.

Patch at 672cddc64fc96f00d54f8f50dde9035f7dadddaa.

**Comment by nfeske** [comment]
Thanks @ehmry for the quick response. I merged your patch. We are still free to revive your port once the need arises.
