### ISSUE TITLE
Update and package Chuck

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#104]
The Chuck port needs to be updated for the new system APIs. Chuck should be packaged because it is quite a powerful toy. It could be part of a demo showcase, but it still needs some work to enable the interactive features. If I knew how to use it better I would try and compose a Genode boot-up theme.

**Comment by ehmry** [comment]
Fixed at fe8861d9eb2493b689e46a250bd01e80c5199ed6, package at `ehmry/pkg/x86_64/chuck/2018-05-10`.

**Comment by nfeske** [comment]
Cool! Thanks for the update. Merged to master.
