### ISSUE TITLE
fractal display program

### ISSUE THREAD

**Issue by zorodc** [genodelabs/genode-world#109]
A program that can display fractals in a Nitpicker window.

**Comment by nfeske** [comment]
Very nice!

Would you mind squashing the commits into a single one (e.g., using `git rebase -i`)?

I'm wondering, why is stdcxx evil? ;-)

**Comment by nfeske** [comment]
BTW, as a good practice, we'd like to keep the first line of the commit message (the title) as short as 50 characters. This way, the messages are displayed completely when showing only commit overviews (or at the commits referenced within GitHub's web interface).

**Comment by nfeske** [comment]
I merged the latest version to master. As a minor cosmetic change, I added a newline below the first line of the commit message. This formatting is common practice to visually separate the first line (title) from the rest (description).

Commit cce8cb6659fcb049b0031409c73c9bd4e7b4c2ef adjusts the run script to fetch all components except the actual Julia fractal from the depot. This way, it works nicely on NOVA and the other kernels now. @zorodc Do you approve?

**Comment by zorodc** [comment]
@nfeske Of course! The patch looks good. Thanks for cleaning up after my naive run script crafting.

**Comment by nfeske** [comment]
Thanks for the response. I added my follow-up commit to master now. May we close the issue? For any new addition, we can open another one.

**Comment by zorodc** [comment]
Ah, of course. Marking closed.
