### ISSUE TITLE
jdk: get Java ready for Genode 19.02

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode-world#136]

**Comment by nfeske** [comment]
Related to https://github.com/genodelabs/genode/issues/3153

**Comment by ssumpf** [comment]
@nfeske c863691 contains the current OpenJDK version.

**Comment by nfeske** [comment]
The `java.run` script produces the following output:

```
[init -> java] Error: ROM-session creation failed (ram_quota=6144, cap_quota=3, label="classes.tar")
[init -> java] Error: Could not open ROM session for "classes.tar"
[init -> java] Error: failed to create <tar> VFS node
[init -> java] Error: 	name="classes.tar"
[init -> java] Error: ROM-session creation failed (ram_quota=6144, cap_quota=3, label="hello.tar")
[init -> java] Error: Could not open ROM session for "hello.tar"
[init -> java] Error: failed to create <tar> VFS node
[init -> java] Error: 	name="hello.tar"
[init -> java] using the pipe libc plugin
[init -> java] Error: Unable to access jarfile hello.jar
```

Would you consider changing the run script in a way that all batteries are included to see the hello-world message, and replacing the `run_genode_until forever` with success condition?

**Comment by ssumpf** [comment]
@nfeske: Fixed with 6a01c1a.

**Comment by nfeske** [comment]
Thanks for the fixup. Now it works fine. I like that the stats are enabled in the scenario - this is quite cool to see.

I merged the squashed commit to master.

**Comment by ssumpf** [comment]
@nfeske: I've added package support to the `java.run` script and commited the 'boot2java.run' script. So please consider a4d5b2b and 36c6334 for Genode world.

**Comment by nfeske** [comment]
This looks very nice! I merged both commits to master.
