### ISSUE TITLE
gtotp_report does not build on ARM

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode-world#142]
There are a series of build errors when building the archive for ARM. E.g., `bin/arm_v7a/gtotp_report`:

```
error: inlining failed in call to always_inline ‘uint32x4_t vaddq_u32(uint32x4_t, uint32x4_t)’: target specific option mismatch

... many more lines like this ...
```

@ehmry Could you please have a look?

**Comment by ehmry** [comment]
Fix at 41c2c7f60d5eaa315110447e63b4b7e01288d02c
