### ISSUE TITLE
jdk: add missing network components

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode-world#150]
required for SSL and client connections

**Comment by nfeske** [comment]
Should I only cherry pick the single commit? I'm asking because it does not cleanly apply onto master. Or should I merge the other commits on your branch as well?

**Comment by nfeske** [comment]
@ssumpf can you please clarify?

**Comment by ssumpf** [comment]
@ssumpf: I will have a look. For some reason I don't get any emails for this issue.

**Comment by ssumpf** [comment]
@nfeske: 493de72 should work for master. The other commits are project related and not meant for staging.

**Comment by nfeske** [comment]
Thanks for updating the commit. I merged it into master.
