### ISSUE TITLE
glib: compile error with current Genode staging branch

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode-world#168]
When building 'make LIB=glib' with the current Genode staging branch, the following error occurs:

```
    COMPILE  gconvert.o
/.../contrib/glib-9ff628584b6bb7848f721e624e8ea3e1111c9e7b/src/lib/glib/glib/gconvert.c:55:2: error: #error GNU libiconv in use but included iconv.h not from libiconv
 #error GNU libiconv in use but included iconv.h not from libiconv
  ^~~~~
```

**Comment by m-stein** [comment]
I've created two commits that enable me to run ``make LIB="glib"`` without errors:

900cf30 glib: fix "no such instruction" in symbol file
3af91a2 glib: don't assume GNU libiconv

**Comment by m-stein** [comment]
Meh, but the glib test doesn't run yet.

**Comment by m-stein** [comment]
I had to adapt a commit and add another one:
b00d4ad run/glib: remove pthread.lib.so module
60c26b4 glib: fix "no such instruction" in symbol file
3af91a2 glib: don't assume GNU libiconv

With this, I can compile the glib test but it fails with:
```
[init -> test-glib] GLib (gthread-posix.c): Unexpected error from C library during 'pthread_mutex_init': Invalid argument.  Aborting.
```
Glib calls ``pthread_mutex_init`` with the argument ``PTHREAD_MUTEX_ADAPTIVE_NP`` but it appears that we support only ``*_NORMAL``, ``*_ERRORCHECK``, and ``*_RECURSIVE``. I'll investigate this tomorrow.

**Comment by chelmuth** [comment]
I suggest to fix this like follows.
```diff
--- a/repos/libports/src/lib/libc/pthread.cc
+++ b/repos/libports/src/lib/libc/pthread.cc
@@ -735,9 +735,10 @@ extern "C" {
 		pthread_mutextype const type = (!attr || !*attr)
 		                             ? PTHREAD_MUTEX_NORMAL : (*attr)->type;
 		switch (type) {
-		case PTHREAD_MUTEX_NORMAL:     *mutex = new (alloc) Pthread_mutex_normal; break;
-		case PTHREAD_MUTEX_ERRORCHECK: *mutex = new (alloc) Pthread_mutex_errorcheck; break;
-		case PTHREAD_MUTEX_RECURSIVE:  *mutex = new (alloc) Pthread_mutex_recursive; break;
+		case PTHREAD_MUTEX_NORMAL:      *mutex = new (alloc) Pthread_mutex_normal; break;
+		case PTHREAD_MUTEX_ADAPTIVE_NP: *mutex = new (alloc) Pthread_mutex_normal; break;
+		case PTHREAD_MUTEX_ERRORCHECK:  *mutex = new (alloc) Pthread_mutex_errorcheck; break;
+		case PTHREAD_MUTEX_RECURSIVE:   *mutex = new (alloc) Pthread_mutex_recursive; break;
 
 		default:
 			*mutex = nullptr;
```

**Comment by m-stein** [comment]
@chelmuth Thanks a lot!

The glib test succeeds with this and the pthread patch:
9d0ffe4 run/glib: add '/tmp' directory
b00d4ad run/glib: remove pthread.lib.so module
60c26b4 glib: fix "no such instruction" in symbol file
3af91a2 glib: don't assume GNU libiconv

**Comment by chelmuth** [comment]
Should the commits above still merged?

**Comment by nfeske** [comment]
Fixed in master.
