### ISSUE TITLE
gtotp_report archive build fails for arm_v8a

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode-world#184]
The following binary archives currently fail to build for arm_v8a.
```
make[2]: *** [genodelabs/bin/arm_v8a/gtotp_report/2019-06-15] Error 2
make[2]: *** [genodelabs/bin/arm_v8a/umurmur/2019-06-15] Error 2
```

**Comment by cnuke** [comment]
Umurmur cannot be build for ARM64 because the byteswap header is not available on FreeBSD. For the time being adding `REQUIRES` should calm the builder.
