### ISSUE TITLE
fetchurl

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#19]
This is a Nix support component that is also general purpose.

**Comment by nfeske** [comment]
Are you planning to update the commit wrt the double use of the VFS?

**Comment by ehmry** [comment]
Yes, best to wait until I have that fixed and then I will add some logging.

**Comment by ehmry** [comment]
Ok, new version at 1e460cf7bc1ee970e3b721f5572585ee4f8ade88, single VFS, logging, and run script.

**Comment by nfeske** [comment]
Thanks for this useful component!
