### ISSUE TITLE
JDK: fix missing verify.lib.so

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode-world#191]

**Comment by ssumpf** [comment]
@trimpim: It is not missing, it is integrated in `jvm.lib.so`, it just cannot be dlopen`ed but the symbols are in place.

**Comment by chelmuth** [comment]
So, could we still get rid of the warning message?

**Comment by ssumpf** [comment]
@chelmuth: 281c833 gets rid of the error message by making `verify.lib.so` available.

**Comment by trimpim** [comment]
@chelmuth and @ssumpf thanks for you effort, I nearly forgot about this issue because of a lot of other things.

I'm closing this, as there is an other fix for this now.
