### ISSUE TITLE
jdk/java: read from stdin fails (terminal)

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode-world#192]

**Comment by ssumpf** [comment]
@trimpim: b7ba444 fixes the issue for myself.  05608fe adds a delimiter to your test, that leads to the return of the scanner.

**Comment by chelmuth** [comment]
@ssumpf I removed the java_stdin branch from the genodelabs repo. please re-push to your ssumpf repo.

**Comment by ssumpf** [comment]
@chelmuth: Oops, sorry!

**Comment by trimpim** [comment]
@ssumpf thanks, this works like a charm. In my real example I do not use the scanner as I read binary data.

**Comment by ssumpf** [comment]
@chelmuth: Please merge this thing (https://github.com/genodelabs/genode-world/commit/b7ba444169a795dcab5caf405ed03a5672e1ed6f) to world. @trimpim: Thanks for testing.

**Comment by chelmuth** [comment]
I improved the commit with an in-source comment and an extended commit message in f957aa538f817b22bf61500bd844048d4706f78f.

**Comment by ssumpf** [comment]
:+1:
