### ISSUE TITLE
gRPC server assertion during start

### ISSUE THREAD

**Issue by sidhussmann** [genodelabs/genode-world#197]
With Genode 19.08 we had some problems with the gRPC server crashing nondeterministic. Despite our best efforts, we have failed to find that problem so far.

As we heard of some libc/vfs improvements in the current Genode master we decided to try running gRPC server with this branch. The result is a assertion in the gRPC server code concerning a mutex unlock and then a following `Error: thread 'runner' tried to self de-struct - sleeping forever.` , which could indicate the same race condition producing the original symptom.

```
[init -> init -> grpc_server] E0101 00:00:00.021000000       0 sync_posix.cc:74]                     assertion failed: pthread_mutex_unlock(mu) == 0
[init -> init -> grpc_server] Warning: raise: raise not implemented
[init -> init -> grpc_server] Warning: raise: raise not implemented
Warning: invalid signal-context capability
[init -> init -> grpc_server] Error: thread 'runner' tried to self de-struct - sleeping forever.
```

It can be reproduced using base_nova as well as base_linux using `run/grpc-startup` in 88255a7.

The grpc_server also logs following error quite often, which however does not seem to impact the functionality of the gRPC server:

```
Error: pthread_self() called from alien thread named 'runner'
```

Can someone help us pinpoint the problem?

**Comment by ssumpf** [comment]
Fixed withj #196 (use pthreads).
