### ISSUE TITLE
Port of libmbim

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode-world#217]
I will be porting version 1.24.0 which seems to be the most recent stable one.

**Comment by m-stein** [comment]
I'll be using the freedesktop libmbim release as contrib source (https://www.freedesktop.org/software/libmbim/)

**Comment by m-stein** [comment]
Switched to version 1.24.2 that was just released this morning.

**Comment by m-stein** [comment]
``make LIB="libmbim"`` succeeds with these:
70e6f78 Port of libmbim (fetch generated files through new port libmbim_generated)
38bd58b Port of libmbim (libmbim compiles, misses generated files)
d5ca4f3 Port of libmbim (switch to version 1.24.2)
878f8d6 Port of libmbim (compile src/common/*.c)

I must admit that I wanted to do this using GOA. I got stuck with this approach as it worked out that fast. However, bringing it to GOA is on my TODO list and I'm still at getting into GOA in parallel.

**Comment by nfeske** [comment]
Is this feature ready for merging? If yes, would you like to have the commits squashed into one?

**Comment by m-stein** [comment]
I'd love to have a representative test running before merging, which is not the case by now. But I'll mark the issue as fixed when it is.
