### ISSUE TITLE
Port of lemon library is broken due to unreachable URL

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode-world#220]

**Comment by m-stein** [comment]
The organization behind LEMON moved to Github at the end of May:
https://www.coin-or.org/2020/05/29/coin-or-moves-to-github/

But although they have many repos, I can't find one for LEMON...
https://github.com/coin-or

**Comment by m-stein** [comment]
But they host archives of it:
https://www.coin-or.org/download/source/

**Comment by chelmuth** [comment]
It seems the domain is up again.
