### ISSUE TITLE
Enable more functionality in glib port

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-world#223]
The current version of the glib port contains only the bare minimum of functionality. In case of _libmbim_ (cf #217) at least `gio` and `gobject` are required additionally.

**Comment by nfeske** [comment]
BTW, genodelabs/master has been updated today.

**Comment by m-stein** [comment]
I've re-based the glib/libmbim stuff of @cnuke to todays genode/staging and genode-world/master:

https://github.com/m-stein/genode-world/tree/issue_217_Port_of_libmbim
https://github.com/m-stein/genode/tree/issue_3815_Support_LTE_USB_modems_that_speak_the_MBIM_protocol

Note, that the commit decba79e438e117003344b2cfd67e8791bffadfe mentioned above is not self standing but might require former glib/libmbim commits of the topic branch. With the re-based state, I could make all affected libs, targets and run scripts successfully except run/mbimcli which, despite sending many requests and receiving many responses from the modem, gets stuck at a later pointer.

Apparently, this is why @cnuke doesn't want the changes to enter master yet.

**Comment by nfeske** [comment]
I'm not in a hurry but merely was afraid to miss to merge something. If someone points me to the right commits to merge once they are ready, I'm perfectly fine. ;-)

**Comment by chelmuth** [comment]
I'd like to take up @nfeske's comment above and encourage you to point me to a topic branch of commits to merge (may it be lmbim, glib or both).

**Comment by nfeske** [comment]
@cnuke Can we close this issue or are there any further commits that need merging?

**Comment by cnuke** [comment]
@nfeske yes, AFAICT all commits are included in the current master branch.
