### ISSUE TITLE
grpc: 06_if_indextoname.patch do not copy correctly

### ISSUE THREAD

**Issue by Jadovenn** [genodelabs/genode-world#249]
From the if_indextoname man page:
```
The if_indextoname() function returns the name of the network interface corresponding to the interface index ifindex.   
The name is placed in the buffer pointed to by ifname. The buffer must allow for the storage of at least IF_NAMESIZE bytes.
```
The current implementation will just return eth0 without placing it into a memory pointed to by ifname. See `src/lib/grpc/patches/06_if_indextoname.patch`

**Comment by nfeske** [comment]
Thank you. I merged your commit just now.
