### ISSUE TITLE
app/iperf: build creates object files in contrib

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode-world#275]
This disallows to compile from the same sources for different architectures in different build directories.

Possibly it was implemented like this due to wrong example in porting guide in [SRC_CC example](https://github.com/genodelabs/genode/blob/abc9a2f232344dd4322c4529ee733e2f5d83c699/doc/porting_guide.txt#L294).

**Comment by nfeske** [comment]
Fixed in master.
