### ISSUE TITLE
jdk: Revive boot2java scenario

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode-world#284]
The `boot2java` run script was custom tailored for the Nitrogen6 Solox i.MX6 SOC. This makes testing the scenario nearly impossible, and therefore, prone to bit rot. Because we want to make sure networking support in Genode's OpenJDK  is working correctly this issues addresses the following goals in order to make the scenario easily reproducible:
* make `boot2java` work on x86_64
* execute in Qemu using two NIC interfaces
* use Sculpt's new modular approach by configuring the scenario as a `runtime`, and thus, making it work like a run script

**Comment by ssumpf** [comment]
https://github.com/genodelabs/genode/commit/a8bf355856a664ba5966a9f909379f3156df09dc
https://github.com/genodelabs/genode/commit/cca80b56e873249d671a3dc803a008998dc38abd
https://github.com/genodelabs/genode/commit/ac332e3d450d6251b8914a3c41de5184faba40c9
are prerequisite.

**Comment by VolkerVoss** [comment]
Can't waiting for that!

**Comment by ssumpf** [comment]
@nfeske: 0e5ef41 adds the discussed changes.

**Comment by nfeske** [comment]
Thanks a lot! I merged the result as https://github.com/genodelabs/genode-world/commit/cff111bd8f5bc88b81f28bc71facf0319b345643

**Comment by ssumpf** [comment]
@chelmuth: Something like 5114d03?

**Comment by chelmuth** [comment]
Looks good to me. @nfeske?

**Comment by nfeske** [comment]
> Looks good to me. @nfeske?

I would prefer dropping the conditions and just set both environment variables.

**Comment by ssumpf** [comment]
@nfeske: ed2d667 is a version without conditions

**Comment by nfeske** [comment]
Thanks you. I merged the fixup.
