### ISSUE TITLE
qt5_webengine: limit the number of parallel ninja jobs by default

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode-world#305]
Unfortunately, disabling the jumbo build feature in issue #303 did not save enough RAM for the weekly build test to finish. The next approach is to reduce the number of parallel ninja jobs to 16 by default, which should keep the RAM demand for building QtWebEngine below 32 GiB. It stayed a few GiB below that limit in a local test run even with jumbo builds enabled, so I would also enable the jumbo build feature again by default since it improves the building speed more than having more parallel jobs without jumbo build. The new default ninja job limit can be manually overridden with `NINJAJOBS=-jxxx` in the environment or on the `make` command line.

**Comment by cproc** [comment]
Fixed by 928ed96.

**Comment by chelmuth** [comment]
Many thanks, that's great! Merged to staging.
