### ISSUE TITLE
depot: content of libmbim incomplete

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode-world#306]
When testing the mobile_network package on Sculpt 22.10, I stumbled upon a `Linker::Not_found` exception in mbimcli. I thus looked into the libmbim binary which turned out to merely contain stub code. As it turned out, the entire contrib sources were missing in the src archive.

**Comment by jschlatow** [comment]
Fixed by d3592af.

**Comment by chelmuth** [comment]
Merged to staging.
