### ISSUE TITLE
java: RAM resource request while loading large JAR file

### ISSUE THREAD

**Issue by rite** [genodelabs/genode-world#311]
In `src/app/jdk/lib/jvm/os_genode.cpp`, the methods `Vm_region_map::attach_at` and `Vm_region_map::attach_executable` upgrade the environments RAM quota instead of RMs RAM while handling a `Out_of_ram` exception.

**Comment by ssumpf** [comment]
ffdfd0f re-enables the boot2java scenario
6f9d1d7 fixes the issue.

**Comment by nfeske** [comment]
Thank you. I merged both commit to staging.

**Comment by ssumpf** [comment]
Fixed in master.
