### ISSUE TITLE
seoul: fix invocation of isoinfo for UTF-8 systems

### ISSUE THREAD

**Issue by atopia** [genodelabs/genode-world#314]
On my system, the invocation of the isoinfo tool fails because it outputs `Setting input-charset to 'UTF-8' from locale.` to stderr, despite not returning an error code and successfully outputting the
requested `grub.cfg` file.

As a workaround, redirect stderr to `/dev/null` to make the run script work on systems with non-C locale.

**Comment by atopia** [comment]
@alex-ab I would appreciate if you could have a look. I'm not very familiar with run scripts yet, but despite `exec` being a `system()`-like interface, something along `[exec LC_ALL=C command]` does not seem to be supported.

**Comment by chelmuth** [comment]
The redirection of stderr is all right. Your alternative command could be implemented by running a sub-shell like follows.
```tcl
exec sh -c "MYVAR=test commandline"
```
