### ISSUE TITLE
log_tee: fix `LOG session denied because of truncated arguments`

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode-world#335]
While integrating the update to Genode 23.05 in to our scenario where we start `log_tee` in a sub init, we got the following  warning/error for the log sessions of some components.

```
Warning: LOG session denied because of truncated arguments
Error: tcpip: environment LOG session denied (label="tcpip", ram_quota=8192, cap_quota=2, diag=0)
```

During debugging I realized, that the arguments for the LOG sessions going out of `log_tee` were doubled. For components with longer overall labels this led to the observed error.

**Comment by chelmuth** [comment]
Fixed in master.
