### ISSUE TITLE
Add SDL2 mixer and net library

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-world#341]

**Comment by cnuke** [comment]
Commit [361eeef](https://github.com/cnuke/genode-world/commit/361eeeffb1489bea263b31cd32574c6fa6176b01) and [cb287a3](https://github.com/cnuke/genode-world/commit/cb287a364af2164b13bbcef33e8b9283cd9c2304) resolve this issue.

As I have only tested the libraries briefly, e.g. `chocolate-doom-3.0.0` seems to run fine, I am going to add the _fixed_ label after more testing.

**Comment by chelmuth** [comment]
Merged to master.
