### ISSUE TITLE
Extend SDL2 platorm support (resizing + textinput)

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-world#368]

**Comment by jschlatow** [comment]
@cnuke I tested your commits with the updated libvnc (requires SDL2) and sdl_vnc. I made a few modifications to make it more robust and to suppress unknown keysym warnings that popped up at the VNC server. May you have a look whether 97fc0db breaks anything for dhewm3?

**Comment by cnuke** [comment]
@jschlatow thanks for the fixup commit that looks like a nice improvement indeed and works fine with `dhewm3` :+1:.

**Comment by chelmuth** [comment]
Merged the fixup to staging.
