### ISSUE TITLE
update libvnc (fixes server crashes when running pthreads)

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode-world#369]

**Comment by jschlatow** [comment]
Fixed by c3ebc89

**Comment by jschlatow** [comment]
@chelmuth Thanks for merging. I just pushed fixup commit 59f458b that re-enables support for password authentication.

**Comment by chelmuth** [comment]
Can we close this issue as referenced commits were merged to master?

**Comment by jschlatow** [comment]
Yes, closing it.
