### ISSUE TITLE
Time-base One-Time Password generator

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#45]
I've written a Google Authenticator compatible password generator as a VFS plugin.

Implementing the generator as a special file was the most generic way I could think of to do it. This allows the generator to be used most anywhere, you can cat it with Noux, you can serve the file over http, you can use it programmatically anywhere you can read files.

Tested with Github and a few other services.

**Comment by ehmry** [comment]
I've noticed it is a bit slow, which I assume comes from reading the hardware, if the VFS constructor where passed Env, then a timer session would probably be used to update a timestamp, and then there would be a signal handler to re-read the RTC on a timeout to account for timer rollover and drift.

**Comment by chelmuth** [comment]
Sounds similar to what we need in libc for `gettimeofday()`.

**Comment by ehmry** [comment]
Now that I think about it, waking an entrypoint is unnecessary, one need only check for the presence of a received signal.

**Comment by chelmuth** [comment]
I had an idea over lunch: Is it correct that we only need gettimeofday-like values? If yes, wouldn't it be sufficient to define `t0` with `Rtc::current_time()` and `Timer::elapsed_ms()` and later just calculate `t_now` by `t0 + Timer::elapsed_ms()`?

**Comment by ehmry** [comment]
I think the only problem is that the timer rolls over after like two months.
