### ISSUE TITLE
fb_upsale: refresh on resize, fix refresh dimensions

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#46]

**Comment by ehmry** [comment]
Fb_upscale has some serious synchronization problems with Dosbox, I will have to poke around in Dosbox and look at the timing at some point.

**Comment by nfeske** [comment]
I wonder, is this patch + fixup intended for being merged yet?

**Comment by ehmry** [comment]
@nfeske Yes these two commits are ready. A problem with SDL remains but I'm not what it is yet, maybe partial refreshes.
