### ISSUE TITLE
Audio synthesis

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#47]
This is a long term project, but I would like to be able to generate sound from arbitrary system events. Right now my thought is to regex LOG sessions and generate events that can be fed to a synthesizer or something that can play back samples.

I did a bit of research and [Chuck](http://chuck.cs.princeton.edu/) seems like the best choice for generating sound, I think the next step would then perhaps to make an [OSC](https://en.wikipedia.org/wiki/Open_Sound_Control) session to feed it events with.

I will be porting Chuck when I have the time, unless anyone has a better idea.

**Comment by ssumpf** [comment]
@ehmry: Cool idea!

**Comment by nfeske** [comment]
You keep coming up with extremely funny and cool ideas! :-)

**Comment by ehmry** [comment]
I have the Chuck language ported, and it is ready to play with, so I would say this issue can close and later I will open some related issues later.

There are a few problems I should to point out:

The on-the-fly shell is disabled but should work fine when the asynchronous VFS plugin gets into libc and stdin and stdout can be hooked to a terminal.

The HID input for creating instruments is disabled until I'm sure the latency is down.

Audio_in is a bit funny, I seem to need to open the input as mono from audio_drv but the audio library needs to open the same number of channels for input and output.

It might be nice to put Chuck between the audio driver and an application to apply filters to audio streams but this is going to require a patchbay component or serving Audio_in from Chuck. 

I think I would prefer channel session being opened with both textual and numeric ids. Genode is probably not the best choice of platform for a realtime audio workstation but having abstract channel ids would be nice.

I thought a bit about MIDI and I think that should either be a packet stream interface, or a special file serving dynamically generated MIDI file format chucks. Anyway, maybe MIDI is not so important.

**Comment by ehmry** [comment]
Also, I still need make an example runscript.

**Comment by nfeske** [comment]
Will you give me a sign when I should go ahead with merging the commit series?

**Comment by ehmry** [comment]
@nfeske It is ready, I wanted a run scenario but settled for a README. Running without a normal file-system got too complicated (the compiler doesn't like zero-padded ROM files).

**Comment by nfeske** [comment]
Do you see a chance to reduce the size of  src/app/chuck/patch? It is over 2400 lines but it seems to me that for the most part, the patch removes code from the contrib source. Would it be possible to shadow those header files via the INC_DIR order instead? Or alternatively, assemble a custom include directory at build time? For a reference on how to do the latter, you may take a look at https://github.com/genodelabs/genode/blob/master/repos/base-okl4/lib/mk/platform.inc. Here, the contrib code also comes with several headers that conflict with our own. Instead of removing them from the contrib code, we create a tree of symlinks that looks like the original one except for the files we don't want.

**Comment by ehmry** [comment]
Yes, will do.

**Comment by ehmry** [comment]
Ok, I cut the fat on the liblo and chuck ports, should be good to merge.

**Comment by nfeske** [comment]
Thanks a lot! I merged the patch series into master now.

**Comment by ehmry** [comment]
There is an initial implementation of arbitrary audio triggered by log messages at 4b923399e71ace65bd371aa5f2d834ca15d89aa5, but I need to test input event generation more and play around with synthesis before I can make a really good demo.
