### ISSUE TITLE
Libretro frontend

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#52]
I've decided my emulator work can be merged into this repository. Audio is not working, or atleast it is not accurate at non-native sampling rates, which is not a problem for the Pi.

I've included two run scenarios with homebrew games on the NES and SNES, both with audio disabled.

The Libretro explanation: https://www.libretro.com/index.php/api/

**Comment by nfeske** [comment]
Very cool! Both run scripts work nicely on base-linux. :-) I just added a smallish fix for a size_t ambiguity and merged your patches.

**Comment by nfeske** [comment]
Interstingly, the libretro frontend triggered an issue that was hiding in the `Framebuffer::Connection`. Strange that this is the first time it caused any problems: https://github.com/genodelabs/genode/commit/e3c9fc49eaeaae4637e06fa693853473a1ffc54c
