### ISSUE TITLE
Adaptation to removal of component_entry_point library

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode-world#57]
In https://github.com/genodelabs/genode/issues/2199, we simplify the component-startup procedure, which requires minor adjustments of components.

**Comment by nfeske** [comment]
Commit 28fd1f7090e49ecdbfca91fb6dd8dbc31a793bf7 adjusts the world components accordingly. I will merge it as soon as the Genode change enters the master branch (it is on staging right now).

**Comment by ehmry** [comment]
I an update for synergy and the Zynq drivers. I was not able to successfully run the synergy scenario, but it compiles and runs as well as i does on master. Zync I was not able to compile because I lack the right toolchain.

**Comment by nfeske** [comment]
Thanks for revisiting this issue. I merged the "Adaptation" and synergy commits. Maybe @ValiValpas would like to give your zynq adaptation a try?
