### ISSUE TITLE
retro_frontend: audio sample rate conversion

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#60]
I threw in new game too.

**Comment by ehmry** [comment]
I should mention that this and #61 need to wait for the new Libc::Component API.

**Comment by ehmry** [comment]
Rebasing without the game, still doesn't work well on NOVA, I suspect this is an issue with playback signals from the audio driver.

**Comment by nfeske** [comment]
Will you give me a hint once you'd like me to merge the branch?

**Comment by ehmry** [comment]
Yes, ready, my issue60 branch, 1d7acb886f832407a10aee0d798eaabdc7a51d29, e7fe27935548370923076fa8180f44dfc2d2d89c, 6350040cb330f7d2032e304508b2b57c0f473f11, b914fb1fad1cc64411aca557287143d641d58aff, 313e9e655d8c98cb6433e72f92d9817282e08486, fe012bbbb794961c71236e3602e3ab727012273c
