### ISSUE TITLE
port tyrquake

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#61]
ping @cnuke

**Comment by ehmry** [comment]
The run scenario seems to expect to be driven with a gamepad so the controls are funny, but the engine works.

**Comment by ehmry** [comment]
Rebasing this issue, e243b55079bfcb55e9cac478d2c0a979ed0f14f4 is the relevant commit, but requires changes to #60 to load properly.

**Comment by nfeske** [comment]
Do you see a chance of using the `framebuffer_app.inc` (https://github.com/genodelabs/genode-world/blob/master/run/framebuffer_app.inc) as a framework for such run scripts? It would help to reduce code duplications across the run scripts. I.e., I would love to keep all the device-driver magic at a single place (or a few places).

**Comment by ehmry** [comment]
Yes, I will make a note to use it and adapt the old scripts next time.
