### ISSUE TITLE
transparent log overlay demo

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#69]
This is a demo of how I view my logs without SOL.

Requires https://github.com/genodelabs/genode/issues/2348.

**Comment by nfeske** [comment]
That's a super cool effect! I especially like the after-glowing of the pushed-to-back layer when fading out.

**Comment by nfeske** [comment]
Even though your patch depends on your rom-filter modification, which is not on genode/master yet, I merged it to world already.
