### ISSUE TITLE
Lzip ROM decompressor

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#70]
At first I wanted to write a 7zip VFS plugin, but after giving it some thought I realized a more general purpose tool would process XZ compressed tarballs. I looked at the XZ format and found it unsuitably complex, which lead me to Lzip, which has a more compatible philosophy. 

My final product is the ``lz_rom`` (name is negotiable) server that reads compressed data from a VFS and produces uncompressed ROM sessions. This can significantly reduce relative storage costs, but because the compressor is CPU-bound, large files like ``qt5_webcore.lib.so`` become quite expensive to process. I am considering another component using the I/O-bound Lz4 decompressor, but I believe that the entire file must be streamed to find the final uncompressed size, which is required before a ROM dataspace can be allocated.

An unintended use case that I have found is to stack ``fs_rom`` in front of ``lz_rom`` with ``rom_fallback`` to keep compressed backups of components. The uncompressed file will be fetched first, say a version from staging, and a release version may be keep compressed. To revert to the older version, the uncompressed version is removed. 

Some numbers for comparison.

File | Size | Ratio
-|-|-
coreutils.tar | 12421120 | 100%
coreutils.tar.lz4 | 7734747 | 62.27%
coreutils.tar.gz | 5618158 | 45.23%
coreutils.tar.bz2 | 2467519 | 19.86%
**coreutils.tar.lz** | **973324** | **07.83%**
coreutils.tar.xz | 966480 | 07.78%

(Xz is smaller, probably because it contains optimizations for binaries, which naturally increases complexity.)

http://www.nongnu.org/lzip/

**Comment by nfeske** [comment]
The numbers are impressive! This looks like a handy component.

**Comment by nfeske** [comment]
I wonder, once we add the ability to use the VFS by VFS plugins, may it be worth considering the implementation of similar functionality as a VFS plugin? Does the lz format support some kind of seek operation? I think it would be quite cool to chain a tar and a lz VFS plugin in arbitrary VFS-using components.

**Comment by nfeske** [comment]
As a minor side note while browsing your patch, the following code could make use of the `String` constructor instead of relying on a format string (I plan to remove format-string support from the Genode API futher down the road):

```
char new_label[request_label.capacity()];
snprintf(new_label, sizeof(new_label), "/%s.lz", request_label.string());
Session_label const filename(new_label);
```

You could instead do:

```
Session_label const filename(String<request_label.capacity()>("/", request_label));
```
