### ISSUE TITLE
app/pike_loader: mouse driven loader client

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#71]

**Comment by ehmry** [comment]
This is a toy component to recreate some of the feel of Plan 9 on Genode.

There is a short demo here: https://vimeo.com/213455616
And the a demo of the original Plan9 here: https://vimeo.com/7511980

The outstanding issue is that it creates new subsystems but with the loader server, and it only keeps one loader subsystem alive at a time. So either it could be used with a re-attachable terminal component, or with a menu that communicated with a more robust subsystem manager.

**Comment by nfeske** [comment]
I am amazed about your creative and unexpected ways of using the existing components! Your pike_loader is really tiny and opens up a completely new option for a Genode-based user interface. Thank you also for posting the demos.
