### ISSUE TITLE
remove native snprintf calls

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#72]
@nfeske I'm glad you pointed out that ``snprintf`` is largely unnecessary (#70). This patch replaces all native ``snprintf`` calls in world with ``Genode::string`` constructors.

**Comment by nfeske** [comment]
Thank you for the very welcome cleanup!

I just noticed that your last few commits - including your current one - have a quite strange email address (something about spam.works). Would you mind adjusting them with your real email address?

Unfortunately, some commits with this email addresses already entered the master branch. :-/ I am not quite sure what to do about it.

**Comment by ehmry** [comment]
Its a valid email, but I revert the address at b8c73cbebedd6851327e02a2b9410370de29d5bc.

**Comment by nfeske** [comment]
Thanks. I merged the new version just now.
