### ISSUE TITLE
upgrade components and scenarios to 17.05 release

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#74]

**Comment by nfeske** [comment]
Thanks Emery and Stefan! I wonder, should I go forward and cherry pick all commits tagged with the issue to master?

**Comment by ehmry** [comment]
@nfeske You may pick all of mine, but there are a few more things to do.

**Comment by nfeske** [comment]
Thanks @ehmry and @ValiValpas for the updates! @ehmry could you rebase the commit 26858f8df87311cf123182b67c4478672f8fcab5 to the current master?

**Comment by ehmry** [comment]
@nfeske rebased at 4e0d596d428d5ec7133d085bf2c2922974ca4cfb,

**Comment by nfeske** [comment]
@ehmry thanks!

**Comment by ehmry** [comment]
And the TestU01 tests for Jitterentropy updated at cfcb1ca560ad8a502c74d82616abe89a222be624

**Comment by ehmry** [comment]
And a Chuck update at b822e08c2d2b04cf86159e3006aee15254fc4c1c

**Comment by nfeske** [comment]
Merged it just now. Thanks a lot!

**Comment by ehmry** [comment]
Thats it is for now, I may have some more by tomorrow.
