### ISSUE TITLE
blk_shred: utility for wiping block media

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#81]
I have a small project to squeeze in, it fills a block session with noise. I don't want to qualify the difference between noise and entropy or randomness, but it will definitely overwrite your data. Can be used to destroy or prepare VMs, or maybe someday in as a distributable boot image.

Inspired by [Darik's Boot and Nuke](https://en.wikipedia.org/wiki/Darik's_Boot_and_Nuke).

**Comment by nfeske** [comment]
Merged to master. I didn't try out the run script though. ;-)
