### ISSUE TITLE
eigentor: adapt to 17.08 release

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode-world#83]

**Comment by m-stein** [comment]
11682cc eigentor: adapt to 17.08 release

**Comment by nfeske** [comment]
How does the commit relate to 8eeda9d8760e0afdf1d04377880d84745b84ec4a on the master branch?

**Comment by skalk** [comment]
@nfeske I was updating TOR and tested it via Genode/Linux using run/tor_lx successfully, further investigated eigentor.run, but it failed with same resources delegated to TOR and clients, then I asked m-stein to have a look at the integrated scenario using nic_router, and here we are

**Comment by nfeske** [comment]
Alright. I merged @m-stein's commit right away.
