### ISSUE TITLE
hotkey_edit: launch components by hotkey via XML editing

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#86]
This would be the first real component written in Nim. Requires a patched compiler, see https://github.com/genodelabs/genode/issues/2545

The libraries at *include/nim* are still draft modules, but functional.

**Comment by ehmry** [comment]
Everything is ready at my `issue86_hotkey` branch, run scenario works best on Linux, but tested on real hardware.

**Comment by nfeske** [comment]
I am impressed by the scope of your work! I merged your commits to master.
