### ISSUE TITLE
retro_frontend refactor

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#89]
I've refactored and rearranged most of `retro_frontend` to support keyboards and multiple controllers. The input remapping from Genode to Libretro is now configurable, which is a big improvement over remapping Genode codes to match static mapping from Genode codes to Libretro codes. I have tested using multiple *Input* sessions but I have not tested actual two-player gameplay.

There also a README now, so I would say the frontend is out of 'beta'.

**Comment by ehmry** [comment]
Patch at 45efb008829b06fc7eec08b5514fd02d7b3f0b3e.

**Comment by nfeske** [comment]
Very nice! I wonder, would you like to cover it in the release notes of the upcoming Genode version?

Seeing that you removed the use of the input_remap component, could we possibly remove the component (and also the old input_merger) altogether? I think that they are superseded by the input_filter, anyway.

**Comment by nfeske** [comment]
Merged to master.

**Comment by ehmry** [comment]
@nfeske I can write something brief for the release notes, and yes, I think input_remap can be removed. I will prepare a batch a of commits for the 17.11 release and create a new issue here.
