### ISSUE TITLE
tftp_rom

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#9]
My new AMT machine should get here today or tomorrow, but in the meantime, I've been using this to test scenarios on real hardware.

This is only rfc1350 (1992), so the maximum supported file size is 32MB. Eventually the block size option from later versions will need to be implemented.

Requires https://github.com/genodelabs/genode/issues/1888

**Comment by nfeske** [comment]
Very cool! Now I see where your request for the delayed dataspace delivery comes from. :-)
