### ISSUE TITLE
17.11

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#91]

**Comment by ehmry** [comment]
I have patches for the 17.11 release on my 'pre17.11' branch.

**Comment by nfeske** [comment]
Fantastic! I merged you patch series to master.

**Comment by ehmry** [comment]
@cnuke noticed that a I failed to include the API recipe for Libretro, patch at 6f7a231df0d3751b0f63fc1b20d7c1dc0644d52c.

**Comment by nfeske** [comment]
@ehmry Thanks for the follow-up commit. I just added it to master.

**Comment by ValiValpas** [comment]
I updated the specs for the zynq boards (aeac4df). Please note that this also relates to a pull request in the main repository (https://github.com/genodelabs/genode/pull/2615).

**Comment by nfeske** [comment]
@ValiValpas Thanks! I merged both commits to master.
