### ISSUE TITLE
Nim libraries update

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#96]
I have an update for the Nim library modules and a new module for server utilities. The world repo may probably have some Nim servers in the future but for now I have an example of session creation [here](https://github.com/ehmry/genode-ipfs/blob/ed974dd99c2967a9dbcd1359501e943b895cdd09/src/server/ipld_fs/ipld_fs.nim#L359).

**Comment by nfeske** [comment]
Merged to master.
