### ISSUE TITLE
FLIF image viewer

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode-world#97]
I have the reference library of the FLIF lossless image format ported and a simple viewer application that loads images from a directory in lexigraphic order.

Right now there is no support for re-dimensioning images into Nitpicker views, but I am still pondering what the right interface for it is. Anyway, I will have a demo at FOSDEM.

**Comment by ehmry** [comment]
Read to merge from my **issue97_flif** branch.

**Comment by ehmry** [comment]
Yes, go ahead.

**Comment by nfeske** [comment]
It's my pleasure! :-)
